# Generated by Django 5.2.14 on 2026-07-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
