# Generated by Django 5.2.14 on 2026-07-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_posted_by_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.IntegerField(null=True),
        ),
    ]
