# Generated by Django 5.2.14 on 2026-07-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='remark',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
