# Generated by Django 5.2.14 on 2026-07-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bidding',
            field=models.BooleanField(default=True),
        ),
    ]
